spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
greetting-service:
  greeting: "Pronto 3"
  default-value: "mondo!"
